services:
  brno:
    image: ghcr.io/adamkankovsky/simulation-brno:latest
    network_mode: host

  olomouc:
    image: ghcr.io/adamkankovsky/simulation-olomouc:latest
    network_mode: host
    profiles: [olomouc, all]

  most:
    image: ghcr.io/adamkankovsky/simulation-most:latest
    network_mode: host
    profiles: [most, all]
